language: python

python: "3.6.1"

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
      - gcc-4.8  # for reppy build
      - g++-4.8  # for reppy build

before_install:
  - pip install pipreqs
  - pipreqs . --print
  - pipreqs . --savepath requirements.txt

install:
  - CC=gcc-4.8 CXX=g++-4.8 pip install html5lib -r requirements.txt

before_script:
  - pip install pylama coverage nose
  - pip install coveralls

script:
  - pylama
  - coverage run --source=. --omit=tests/* -m nose

after_success: coveralls
